In [3]:
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
import pandas as pd
import numpy as np

In [101]:
def karhunen(data):
    
    # First we calculate the mean of each column
    means = np.zeros(len(data.columns))# for all columns
    for i in range(len(data.columns)):
        means[i] = data.iloc[:, i].mean()
    
    mean_zero = np.zeros(data.shape)
    # Now we substract the corresponding mean to all the values of our dataset
    for j in range(len(data)): # for all instances
       mean_zero[j, :] = data.iloc[j, :] - means
        
    # Now we have to calculate the covariance matrix
    cov = np.zeros((len(data.columns), len(data.columns)))
    for i in range(len(data)): # for all instances
        cov += np.array([mean_zero[i, :]]).T*mean_zero[i, :]
    cov = cov/len(data) # This is our final covariance matrix
    
    # Lastly, we obtain the eigenvalues and its corresponding eigenvectors
    eigenVal, eigenVec = np.linalg.eig(cov)
    
    return means, cov, eigenVal, eigenVec

In [5]:
# As our function performs on dataframes and numpy arrays, we will adapt this info to do so
irisdf = pd.DataFrame(iris.data)

irisdf

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [6]:
# First we calculate the mean of each column
means = np.zeros(len(irisdf.columns))
for i in range(len(irisdf.columns)):
    means[i] = irisdf.iloc[:, i].mean()

In [7]:
means

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [26]:
irisdf.describe().loc['mean', :]

0    5.843333
1    3.057333
2    3.758000
3    1.199333
Name: mean, dtype: float64

In [9]:
mean_zero = np.zeros(irisdf.shape)
# Now we substract the corresponding mean to all the values of our dataset
for j in range(len(irisdf)): # for all instances
   mean_zero[j, :] = irisdf.iloc[j, :] - means

In [11]:
mean_zero.shape

(150, 4)

In [35]:
mean_zero[1, :]

array([-0.94333333, -0.05733333, -2.358     , -0.99933333])

In [13]:
cov = np.zeros((len(irisdf.columns), len(irisdf.columns)))
for i in range(len(irisdf)):
    cov += np.array([mean_zero[i, :]]).T*mean_zero[i, :]

cov = cov/len(irisdf)
    
cov

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

In [41]:
mean_zero[0, :].T*mean_zero[0, :]

array([0.55254444, 0.19595378, 5.560164  , 0.99866711])

In [46]:
np.array([mean_zero[0, :]]).T*mean_zero[0, :]

array([[ 0.55254444, -0.32904889,  1.75278   ,  0.74283778],
       [-0.32904889,  0.19595378, -1.043808  , -0.44237156],
       [ 1.75278   , -1.043808  ,  5.560164  ,  2.356428  ],
       [ 0.74283778, -0.44237156,  2.356428  ,  0.99866711]])

In [18]:
eigenVal, eigenVec = np.linalg.eig(cov)

In [19]:
eigenVal, eigenVec

(array([4.20005343, 0.24105294, 0.0776881 , 0.02367619]),
 array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
        [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
        [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
        [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]]))

In [55]:
X = pd.DataFrame([[1, 2, 1], [2, 3, 1], [3, 5, 1], [2, 2, 1]])
X

0  1  2
0  1  2  1
1  2  3  1
2  3  5  1
3  2  2  1

In [56]:
# First we calculate the mean of each column
means = np.zeros(len(X.columns))
for i in range(len(X.columns)):
    means[i] = X.iloc[:, i].mean()

In [58]:
mean_zero = np.zeros(X.shape)
# Now we substract the corresponding mean to all the values of our dataset
for j in range(len(X)): # for all instances
   mean_zero[j, :] = X.iloc[j, :] - means

In [60]:
cov = np.zeros((len(X.columns), len(X.columns)))
for i in range(len(X)):
    cov += np.array([mean_zero[i, :]]).T*mean_zero[i, :]

cov = cov/len(X)
    
cov

array([[0.5 , 0.75, 0.  ],
       [0.75, 1.5 , 0.  ],
       [0.  , 0.  , 0.  ]])

In [61]:
eigenVal, eigenVec = np.linalg.eig(cov)

eigenVal, eigenVec

(array([0.09861218, 1.90138782, 0.        ]),
 array([[-0.8816746 , -0.47185793,  0.        ],
        [ 0.47185793, -0.8816746 ,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))

In [67]:
v = eigenVec[:, :2]

In [75]:
y = np.dot(v.T, mean_zero.T)

y

array([[ 0.40981667,  0.        ,  0.06204125, -0.47185793],
       [ 1.35353252,  0.        , -2.23520712,  0.8816746 ]])

In [76]:
v.T, mean_zero.T

(array([[-0.8816746 ,  0.47185793,  0.        ],
        [-0.47185793, -0.8816746 ,  0.        ]]),
 array([[-1.,  0.,  1.,  0.],
        [-1.,  0.,  2., -1.],
        [ 0.,  0.,  0.,  0.]]))

In [78]:
six = pd.DataFrame([[0, 1], [3, 5], [5, 4], [5, 6], [8, 7], [9, 7]])

six

0  1
0  0  1
1  3  5
2  5  4
3  5  6
4  8  7
5  9  7

In [81]:
mean_zero, cov, eigenVal, eigenVec = karhunen(six)

In [82]:
eigenVal, eigenVec

(array([12.79492544,  0.5384079 ]),
 array([[ 0.83088802, -0.55643966],
        [ 0.55643966,  0.83088802]]))

In [84]:
v = eigenVec[:, :1]

In [85]:
y = np.dot(v.T, mean_zero.T)

y

array([[-6.38019875, -1.66177604, -0.55643966,  0.55643966,  3.60554339,
         4.43643141]])

In [123]:
means, cov, eigenVal, eigenVec = karhunen(irisdf)

In [124]:
eigenVal, eigenVec

(array([4.20005343, 0.24105294, 0.0776881 , 0.02367619]),
 array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
        [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
        [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
        [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]]))

In [125]:
val = eigenVal[:2]

v = eigenVec[:, :2]

val, v

(array([4.20005343, 0.24105294]),
 array([[ 0.36138659, -0.65658877],
        [-0.08452251, -0.73016143],
        [ 0.85667061,  0.17337266],
        [ 0.3582892 ,  0.07548102]]))

In [126]:
np.dot(v.T, zero.T)

array([[-1.01971563],
       [-0.41842615]])

In [127]:
p1 = np.array([[5.6,3.6,3.1,0.3]])


y1 = np.dot(v.T, (p1 - means).T)

y1

array([[-1.01971563],
       [-0.41842615]])

In [128]:
p2 = np.array([[5.1,4.2,6.3,2.4]])


y2 = np.dot(v.T, (p2 - means).T)

y2

array([[2.24263082],
       [0.18507404]])

In [129]:
p3 = np.array([[4.7,2.8,2.1,1.3]])


y3 = np.dot(v.T, (p3 - means).T)

y3

array([[-1.77572696],
       [ 0.65874125]])

In [130]:
p4 = np.array([[6.3,3.4,3.6,2.1]])


y4 = np.dot(v.T, (p4 - means).T)

y4

array([[ 0.32341534],
       [-0.50945383]])

In [131]:
p5 = np.array([[5.5,2.7,6.5,2.2]])


y5 = np.dot(v.T, (p5 - means).T)

y5

array([[2.61364551],
       [1.03725901]])

In [132]:
# FASTER WAY TO DO IT WITH SCIKIT LEARN
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
ytest=pca.fit(iris.data).transform(np.array([[5.6,3.6,3.1,0.3]])) # for the first point

In [133]:
ytest

array([[-1.01971563,  0.41842615]])

# SECOND PART: Sparse Coding


In [13]:
from sklearn.decomposition import sparse_encode

In [6]:
# We have to define a class-specific dictionary for each class
v0 = irisdf[iris.target == 0]
v1 = irisdf[iris.target == 1]
v2 = irisdf[iris.target == 2]

In [10]:
p1 = np.array([[5.7,4.1,5.2,2.3]])
p2 = np.array([[5.4,3.1,5.7,1.2]])
p3 = np.array([[5.7,2.4,4.0,2.3]])
p4 = np.array([[7.5,2.5,4.2,1.5]])
p5 = np.array([[7.2,2.3,6.5,0.9]])

p1, p2, p3, p4, p5

(array([[5.7, 4.1, 5.2, 2.3]]),
 array([[5.4, 3.1, 5.7, 1.2]]),
 array([[5.7, 2.4, 4. , 2.3]]),
 array([[7.5, 2.5, 4.2, 1.5]]),
 array([[7.2, 2.3, 6.5, 0.9]]))

In [ ]:
# ||x−VTy||2+λ||y||0 , where λ=0.1 FOR EACH POINT AND EACH DICTIONARY

In [44]:
# POINT 1: (5.7,4.1,5.2,2.3)
p1

array([[5.7, 4.1, 5.2, 2.3]])

In [65]:
y10 = sparse_encode(p1,v0,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y11 = sparse_encode(p1,v1,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y12 = sparse_encode(p1,v2,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)

y10, y11, y12

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         -2.52479154,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  4.33691025,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]),
 array([[ 0.        ,  0.        , -1.0980682 ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        , 

In [69]:
np.linalg.norm(p1.T - np.dot(v0.T, y10.T)) + 0.1*np.count_nonzero(y10)

2.895524675669871

In [70]:
np.linalg.norm(p1.T - np.dot(v1.T, y11.T)) + 0.1*np.count_nonzero(y11)

0.5876344163343765

In [71]:
np.linalg.norm(p1.T - np.dot(v2.T, y12.T)) + 0.1*np.count_nonzero(y12)

0.9566490233406224

In [72]:
# POINT 2: (5.4,3.1,5.7,1.2)
p2

array([[5.4, 3.1, 5.7, 1.2]])

In [73]:
y20 = sparse_encode(p2,v0,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y21 = sparse_encode(p2,v1,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y22 = sparse_encode(p2,v2,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)

y20, y21, y22

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         -3.81135121,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  5.75146777,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]),
 array([[ 0.        ,  0.        , -0.71947831,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        , 

In [77]:
np.linalg.norm(p2.T - np.dot(v0.T, y20.T)) + 0.1*np.count_nonzero(y20)

1.946270029380199

In [78]:
np.linalg.norm(p2.T - np.dot(v1.T, y21.T)) + 0.1*np.count_nonzero(y21)

1.0451078596328869

In [79]:
np.linalg.norm(p2.T - np.dot(v2.T, y22.T)) + 0.1*np.count_nonzero(y22)

0.291955023712951

In [80]:
# POINT 3: (5.7,2.4,4.0,2.3)
p3

array([[5.7, 2.4, 4. , 2.3]])

In [81]:
y30 = sparse_encode(p3,v0,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y31 = sparse_encode(p3,v1,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y32 = sparse_encode(p3,v2,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)

y30, y31, y32

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         -3.24613502,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  4.87926816,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]),
 array([[0.        , 0.        , 0.24448989, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.   

In [82]:
np.linalg.norm(p3.T - np.dot(v0.T, y30.T)) + 0.1*np.count_nonzero(y30)

1.7732311232868454

In [83]:
np.linalg.norm(p3.T - np.dot(v1.T, y31.T)) + 0.1*np.count_nonzero(y31)

1.1505824726663358

In [84]:
np.linalg.norm(p3.T - np.dot(v2.T, y32.T)) + 0.1*np.count_nonzero(y32)

0.47638147476208875

In [85]:
# POINT 4: (7.5,2.5,4.2,1.5)
p4

array([[7.5, 2.5, 4.2, 1.5]])

In [86]:
y40 = sparse_encode(p4,v0,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y41 = sparse_encode(p4,v1,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y42 = sparse_encode(p4,v2,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)

y40, y41, y42

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         -1.21455493,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  3.34439087,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]),
 array([[ 1.79325468,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        , 

In [87]:
np.linalg.norm(p4.T - np.dot(v0.T, y40.T)) + 0.1*np.count_nonzero(y40)

2.2454747938429795

In [88]:
np.linalg.norm(p4.T - np.dot(v1.T, y41.T)) + 0.1*np.count_nonzero(y41)

0.7750288179668039

In [89]:
np.linalg.norm(p4.T - np.dot(v2.T, y42.T)) + 0.1*np.count_nonzero(y42)

1.4782565689517333

In [90]:
# POINT 5: (7.2,2.3,6.5,0.9)
p5

array([[7.2, 2.3, 6.5, 0.9]])

In [91]:
y50 = sparse_encode(p5,v0,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y51 = sparse_encode(p5,v1,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)
y52 = sparse_encode(p5,v2,algorithm='omp',n_nonzero_coefs=2,alpha=1.000000e-05)

y50, y51, y52

(array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         -5.06052183,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  7.42218596,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]),
 array([[ 0.        ,  0.        ,  2.98510543,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        , 

In [92]:
np.linalg.norm(p5.T - np.dot(v0.T, y50.T)) + 0.1*np.count_nonzero(y50)

1.8419323018480012

In [93]:
np.linalg.norm(p5.T - np.dot(v1.T, y51.T)) + 0.1*np.count_nonzero(y51)

0.9353742146224788

In [94]:
np.linalg.norm(p5.T - np.dot(v2.T, y52.T)) + 0.1*np.count_nonzero(y52)

1.4302841704759561